---
- hosts: nexus
  gather_facts: false
  remote_user: pi
  roles:
    - nexus  

- hosts: gitlab
  become: true
  remote_user: pi
  roles:
    - geerlingguy.gitlab

- hosts: gateway
  become: true
  remote_user: pi
  roles:
    - access-point
