---
- name: Check if nexus is installed
  stat: path=/etc/init.d/nexusd
  register: nexus_installed  
- block:
  - name: Create nexus folder
    file:
      path: /home/pi/nexus
      state: directory
      mode: 0777
  - unarchive:
      src: http://download.sonatype.com/nexus/3/nexus-3.4.0-02-unix.tar.gz
      dest: /home/pi/nexus
      remote_src: true
      creates: /home/pi/nexus/nexus-3.4.0-02
  - name: Delete Nexus archive
    file:
      path: /home/pi/nexus/nexus-3.4.0-02.unix.tar.gz
      state: absent
  - name: Update min heapspace
    replace:
      path: /home/pi/nexus/nexus-3.4.0-02/bin/nexus.vmoptions
      regexp: "-Xms.*M"
      replace: "-Xms256M"
  - name: Update max heapspace
    replace:
      path: /home/pi/nexus/nexus-3.4.0-02/bin/nexus.vmoptions
      regexp: "-Xmx.*M"
      replace: "-Xmx256M"
  - name: Create Nexus service
    become: yes
    template:
      src: templates/nexusd.j2
      dest: /etc/init.d/nexusd
      owner: pi
      mode: 0755
  when: not nexus_installed.stat.exists
- name: Ensure nexus is started
  become: yes
  systemd:
    name: nexusd
    daemon_reload: yes
    state: started
